language: android

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - platform-tools
    - tools
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  
jdk:
  - oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=19
    - ANDROID_TARGET=21
    - ANDROID_TARGET=22

script:
  - ./scripts/travis_instrumentation.sh
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
